### ISSUE TITLE
Remove the "Easter Egg"

### ISSUE THREAD

**Issue by Antirhinnum** [RyanMakesMods/FasterBuilding#1]
https://forums.terraria.org/index.php?threads/mod-keeps-telling-me-to-join-a-discord-server-and-i-cant-find-which-one-it-is.101336/

It's obtrusive, annoying, and adds nothing - And most, if not all, players don't want to go through their mods list trying to find the one mod that sometimes replaces the main menu music with an annoying drone. _Especially_ if it's being caused by a small and otherwise useful QoL mod.

**Comment by RighteousRyan1** [comment]
Already taken care of. If you had updated in the past ~6 hours you would know that I removed said easter egg.

**Comment by Antirhinnum** [comment]
Ah, alright. Sorry about that, then.
